// 工具数据API - v6.0 完整版（含workflowSteps）
const tools = [
  // ===== AI入门 - 问答式AI =====
  { id: '1', name: 'ChatGPT', icon: '💬', category: '问答式AI', subcategory: '通用AI',
    description: 'OpenAI开发的AI对话工具，适合日常问答和内容创作',
    scenes: ['ai-entry', 'ai-office', 'ai-create', 'ai-study'],
    price: '免费/付费', priceDetail: '免费版GPT-3.5，付费版GPT-4约20$/月',
    difficulty: '入门', network: '🌐 全球', mobile: 'iOS/Android',
    pros: '功能全面、社区活跃、插件生态丰富',
    cons: '需要网络工具、国内支付不便',
    features: ['智能对话', '文章写作', '代码生成', '翻译', '数据分析'],
    workflow: '提示词工程：描述问题 → AI回答 → 优化提示词 → 获得更好结果',
    workflowSteps: [
      { step: 1, title: '描述问题', desc: '用清晰的语言描述你的问题' },
      { step: 2, title: 'AI回答', desc: '获取AI的初始回答' },
      { step: 3, title: '优化提示词', desc: '根据回答质量调整提示词' },
      { step: 4, title: '获得结果', desc: '获得更准确满意的答案' }
    ],
    openclaw_practice: '通过 OpenAI API skill 调用接口',
    website: 'https://chat.openai.com', sort: 1 },

  { id: '2', name: 'Claude', icon: '🧠', category: '问答式AI', subcategory: '通用AI',
    description: 'Anthropic开发的AI助手，擅长推理和复杂分析，超长上下文',
    scenes: ['ai-entry', 'ai-office', 'ai-study'],
    price: '免费', priceDetail: '免费使用，付费版约25$/月',
    difficulty: '入门', network: '🌐 全球', mobile: 'iOS/Android',
    pros: '推理能力强、长文本处理优秀、输出安全',
    cons: '需要网络工具、国内支付不便',
    features: ['深度推理', '长文本分析', '代码审查', '创意写作'],
    workflow: '深度推理：提出复杂问题 → AI分析 → 追问细节 → 获得深入解答',
    workflowSteps: [
      { step: 1, title: '提出问题', desc: '输入复杂的分析性问题' },
      { step: 2, title: 'AI分析', desc: '获取深度分析和推理过程' },
      { step: 3, title: '追问细节', desc: '针对关键点进一步提问' },
      { step: 4, title: '深入解答', desc: '获得全面深入的答案' }
    ],
    openclaw_practice: '通过 Anthropic API skill 调用',
    website: 'https://claude.ai', sort: 2 },

  { id: '3', name: 'Gemini', icon: '🌟', category: '问答式AI', subcategory: '多模态AI',
    description: 'Google推出的多模态AI，支持图像理解和生成',
    scenes: ['ai-entry', 'ai-create'],
    price: '免费', priceDetail: '免费版有限额，付费版约20$/月',
    difficulty: '入门', network: '🌐 全球', mobile: 'iOS/Android',
    pros: '多模态能力强、Google生态集成、免费额度多',
    cons: '需要网络工具、偶尔不稳定',
    features: ['图像理解', '视频分析', '代码生成', '语音交互'],
    workflow: '多模态交互：文本+图像 → 综合理解 → 多形式输出',
    workflowSteps: [
      { step: 1, title: '输入内容', desc: '同时输入文本和图像' },
      { step: 2, title: '综合理解', desc: 'AI理解多模态信息' },
      { step: 3, title: '处理输出', desc: '生成文本、图像等多种形式' }
    ],
    openclaw_practice: '通过 Google Gemini API',
    website: 'https://gemini.google.com', sort: 3 },

  { id: '4', name: '通义千问', icon: '🐰', category: '问答式AI', subcategory: '国产AI',
    description: '阿里推出的中文AI助手，针对中文场景优化',
    scenes: ['ai-entry', 'ai-office', 'ai-study'],
    price: '免费', priceDetail: '完全免费',
    difficulty: '入门', network: '🇨🇳 国内', mobile: 'iOS/Android',
    pros: '中文优化好、国内直连、完全免费',
    cons: '英文能力较弱、推理能力不如Claude',
    features: ['中文对话', 'PPT生成', '文档处理', '会议纪要'],
    workflow: '中文办公：PPT大纲 → 自动生成 → AI配图 → 智能排版',
    workflowSteps: [
      { step: 1, title: '输入主题', desc: '描述PPT主题和内容要求' },
      { step: 2, title: 'AI生成大纲', desc: '自动生成PPT结构和大纲' },
      { step: 3, title: 'AI配图', desc: '自动匹配合适的图片' },
      { step: 4, title: '智能排版', desc: '自动优化排版和布局' }
    ],
    openclaw_practice: '通过 阿里云API 集成',
    website: 'https://tongyi.aliyun.com', sort: 4 },

  { id: '5', name: 'Kimi', icon: '🌙', category: '问答式AI', subcategory: '国产AI',
    description: '月之暗面推出的长文本AI，支持超长上下文，200万字',
    scenes: ['ai-entry', 'ai-office', 'ai-study'],
    price: '免费', priceDetail: '免费使用，付费版约50$/月',
    difficulty: '入门', network: '🇨🇳 国内', mobile: 'iOS/Android',
    pros: '长文本能力极强、中文理解好、国内直连',
    cons: '推理能力不如Claude、起步较晚',
    features: ['长文本分析', 'PDF解析', '会议纪要', '资料整理'],
    workflow: '长文本处理：上传文档 → AI总结 → 问答互动 → 深度理解',
    workflowSteps: [
      { step: 1, title: '上传文档', desc: '上传PDF、Word等文档' },
      { step: 2, title: 'AI总结', desc: '自动生成文档摘要' },
      { step: 3, title: '问答互动', desc: '针对内容提问获取详情' },
      { step: 4, title: '深度理解', desc: '获得全面的内容理解' }
    ],
    openclaw_practice: '通过 Kimi API',
    website: 'https://kimi.moonshot.cn', sort: 5 },

  { id: '6', name: '文心一言', icon: '🦅', category: '问答式AI', subcategory: '国产AI',
    description: '百度推出的中文AI助手，文学创作能力强',
    scenes: ['ai-entry', 'ai-office'],
    price: '免费', priceDetail: '免费使用，付费版约60$/年',
    difficulty: '入门', network: '🇨🇳 国内', mobile: 'iOS/Android',
    pros: '中文理解好、国内直连、文学创作能力强',
    cons: '推理能力较弱、回答质量不稳定',
    features: ['文学创作', '文案写作', '知识问答', '图片生成'],
    workflow: '中文创作：输入主题 → AI生成 → 润色修改 → 导出',
    workflowSteps: [
      { step: 1, title: '输入主题', desc: '描述创作主题和要求' },
      { step: 2, title: 'AI生成', desc: '生成初稿内容' },
      { step: 3, title: '润色修改', desc: 'AI辅助润色优化' },
      { step: 4, title: '导出使用', desc: '导出文档使用' }
    ],
    openclaw_practice: '通过 百度文心API',
    website: 'https://yiyan.baidu.com', sort: 6 },

  { id: '7', name: '讯飞星火', icon: '🔥', category: '问答式AI', subcategory: '国产AI',
    description: '科大讯飞推出的AI助手，语音能力突出',
    scenes: ['ai-entry', 'ai-office'],
    price: '免费', priceDetail: '完全免费',
    difficulty: '入门', network: '🇨🇳 国内', mobile: 'iOS/Android',
    pros: '语音能力强、中文理解好、国内直连',
    cons: '推理能力一般、回答有时过于简短',
    features: ['语音输入', '语音合成', '实时翻译', '会议纪要'],
    workflow: '语音交互：语音输入 → AI处理 → 语音输出',
    workflowSteps: [
      { step: 1, title: '语音输入', desc: '通过语音输入问题' },
      { step: 2, title: 'AI处理', desc: '语音转文字并理解处理' },
      { step: 3, title: '语音输出', desc: 'AI回复转为语音播报' }
    ],
    openclaw_practice: '通过 讯飞星火API',
    website: 'https://xinghuo.xfyun.com', sort: 7 },

  { id: '8', name: '腾讯元宝', icon: '🐧', category: '问答式AI', subcategory: '国产AI',
    description: '腾讯推出的AI助手，接入腾讯生态',
    scenes: ['ai-entry', 'ai-office'],
    price: '免费', priceDetail: '完全免费',
    difficulty: '入门', network: '🇨🇳 国内', mobile: 'iOS/Android',
    pros: '腾讯生态集成、国内直连、免费使用',
    cons: '功能相对基础、品牌信任度一般',
    features: ['微信生态集成', '文档处理', 'AI绘图'],
    workflow: '日常问答：输入问题 → AI回答 → 追问优化',
    workflowSteps: [
      { step: 1, title: '输入问题', desc: '在微信中直接提问' },
      { step: 2, title: 'AI回答', desc: '快速获取答案' },
      { step: 3, title: '追问优化', desc: '深入追问获取详情' }
    ],
    openclaw_practice: '通过 腾讯元宝API',
    website: 'https://yuanbao.tencent.com', sort: 8 },

  // ===== AI入门 - AI搜索 =====
  { id: '9', name: 'Perplexity', icon: '🔍', category: 'AI搜索', subcategory: 'AI搜索引擎',
    description: 'AI搜索引擎，结合GPT-4提供实时精准答案',
    scenes: ['ai-entry', 'ai-study'],
    price: '免费', priceDetail: '免费版有限额，付费版约20$/月',
    difficulty: '入门', network: '🌐 全球', mobile: 'iOS/Android',
    pros: '实时联网、答案有来源、学术搜索强',
    cons: '需要网络工具、免费额度有限',
    features: ['实时搜索', '答案引用', '学术论文', '代码搜索'],
    workflow: '学术研究：输入课题 → AI搜索整合 → 获取摘要 → 深入阅读 → 笔记整理',
    workflowSteps: [
      { step: 1, title: '输入课题', desc: '输入研究课题或问题' },
      { step: 2, title: 'AI搜索', desc: '实时搜索互联网资源' },
      { step: 3, title: '获取摘要', desc: 'AI整合信息生成摘要' },
      { step: 4, title: '深入阅读', desc: '点击链接深入了解' },
      { step: 5, title: '笔记整理', desc: '整理要点到笔记' }
    ],
    openclaw_practice: '通过 Perplexity API',
    website: 'https://www.perplexity.ai', sort: 9 },

  { id: '10', name: '秘塔搜索', icon: '🔎', category: 'AI搜索', subcategory: 'AI搜索引擎',
    description: '中文AI搜索引擎，无广告',
    scenes: ['ai-entry', 'ai-study'],
    price: '免费', priceDetail: '完全免费',
    difficulty: '入门', network: '🇨🇳 国内', mobile: 'iOS/Android',
    pros: '中文优化好、无广告、国内直连',
    cons: '功能相对基础、偶尔响应慢',
    features: ['中文搜索', '学术搜索', '追问功能'],
    workflow: '中文搜索：输入问题 → AI整理 → 结构化答案 → 深入了解',
    workflowSteps: [
      { step: 1, title: '输入问题', desc: '用中文输入搜索问题' },
      { step: 2, title: 'AI整理', desc: 'AI整理搜索结果' },
      { step: 3, title: '结构化答案', desc: '以结构化方式呈现答案' },
      { step: 4, title: '深入了解', desc: '追问获取更多信息' }
    ],
    openclaw_practice: '秘塔AI搜索',
    website: 'https://metaso.cn', sort: 10 },

  { id: '11', name: '天工AI搜索', icon: '⚡', category: 'AI搜索', subcategory: 'AI搜索引擎',
    description: '昆仑万维推出的中文AI搜索',
    scenes: ['ai-entry', 'ai-study'],
    price: '免费', priceDetail: '完全免费',
    difficulty: '入门', network: '🇨🇳 国内', mobile: 'iOS/Android',
    pros: '中文优化好、完全免费、国内直连',
    cons: '功能相对基础、搜索结果有限',
    features: ['智能搜索', '内容摘要', '对话式问答'],
    workflow: 'AI搜索：输入查询 → AI整合 → 结构化答案',
    workflowSteps: [
      { step: 1, title: '输入查询', desc: '输入搜索内容' },
      { step: 2, title: 'AI整合', desc: 'AI整合相关信息' },
      { step: 3, title: '结构化答案', desc: '输出结构化答案' }
    ],
    openclaw_practice: '天工AI搜索',
    website: 'https://www.tiangong.cn', sort: 11 },

  // ===== AI入门 - AI模型 =====
  { id: '12', name: 'GPT-4', icon: '🔮', category: 'AI模型', subcategory: '大语言模型',
    description: 'OpenAI最强大的语言模型，适合高质量内容生成',
    scenes: ['ai-entry'],
    price: '付费', priceDetail: '约20$/月(Plus)或按量付费',
    difficulty: '进阶', network: '🌐 全球', mobile: '无',
    pros: '能力最强、插件生态、图像理解',
    cons: '需要网络工具、费用较高',
    features: ['文本生成', '代码编写', '数据分析', '图像理解', '语音合成'],
    workflow: 'API调用：设置角色 → 发送请求 → 处理响应 → 结果优化',
    workflowSteps: [
      { step: 1, title: '设置角色', desc: '定义AI的角色和能力' },
      { step: 2, title: '发送请求', desc: '通过API发送请求' },
      { step: 3, title: '处理响应', desc: '解析AI返回的结果' },
      { step: 4, title: '结果优化', desc: '根据需求调整优化' }
    ],
    openclaw_practice: '通过 OpenAI API skill 调用 GPT-4',
    website: 'https://platform.openai.com', sort: 12 },

  { id: '13', name: 'Claude 3', icon: '📦', category: 'AI模型', subcategory: '大语言模型',
    description: 'Anthropic最新模型，超长上下文200K token',
    scenes: ['ai-entry'],
    price: '付费', priceDetail: '约25$/月或按量付费',
    difficulty: '进阶', network: '🌐 全球', mobile: '无',
    pros: '推理能力强、长上下文、安全性好',
    cons: '需要网络工具、国内支付不便',
    features: ['长文本处理', '代码审查', '数据分析', '安全过滤'],
    workflow: '企业应用：数据分析 → 报告生成 → 决策支持',
    workflowSteps: [
      { step: 1, title: '数据分析', desc: '输入数据让AI分析' },
      { step: 2, title: '报告生成', desc: '自动生成分析报告' },
      { step: 3, title: '决策支持', desc: '提供决策建议' }
    ],
    openclaw_practice: '通过 Claude API',
    website: 'https://www.anthropic.com', sort: 13 },

  // ===== AI办公 - 文档处理 =====
  { id: '14', name: 'Notion AI', icon: '📝', category: '文档处理', subcategory: '笔记软件',
    description: 'Notion内置AI功能，帮助写作和整理笔记',
    scenes: ['ai-office', 'ai-study'],
    price: '付费', priceDetail: '约10$/月',
    difficulty: '入门', network: '🌐 全球', mobile: 'iOS/Android',
    pros: '笔记+AI完美结合、模板丰富、协作方便',
    cons: '需要网络工具、国内访问慢、付费较贵',
    features: ['AI写作', '智能润色', '大纲生成', '翻译', '内容摘要'],
    workflow: '写作工作流：AI生成大纲 → 撰写初稿 → AI润色 → 自动整理 → 导出分享',
    workflowSteps: [
      { step: 1, title: 'AI生成大纲', desc: '输入主题，AI生成文档大纲' },
      { step: 2, title: '撰写初稿', desc: '基于大纲撰写内容' },
      { step: 3, title: 'AI润色', desc: 'AI优化语言和表达' },
      { step: 4, title: '自动整理', desc: 'AI自动整理结构和格式' },
      { step: 5, title: '导出分享', desc: '导出或分享文档' }
    ],
    openclaw_practice: '通过飞书+Notion API 联动',
    website: 'https://notion.so/product/ai', sort: 14 },

  { id: '15', name: 'WPS AI', icon: '📄', category: '文档处理', subcategory: '办公软件',
    description: '金山WPS内置AI，中文办公更顺手',
    scenes: ['ai-office'],
    price: '免费', priceDetail: '部分功能免费，会员约30$/年',
    difficulty: '入门', network: '🇨🇳 国内', mobile: 'iOS/Android',
    pros: '国内可访问、中文优化好、免费功能多',
    cons: 'AI功能相对基础、付费版AI功能有限',
    features: ['AI写作', '智能排版', '内容润色', 'PPT生成', '表格分析'],
    workflow: '文档处理：AI续写 → 智能排版 → 内容润色 → 一键生成',
    workflowSteps: [
      { step: 1, title: 'AI续写', desc: '输入开头，AI续写内容' },
      { step: 2, title: '智能排版', desc: 'AI自动优化排版' },
      { step: 3, title: '内容润色', desc: 'AI优化语言表达' },
      { step: 4, title: '一键生成', desc: '快速生成完整文档' }
    ],
    openclaw_practice: '通过 WPS AI API',
    website: 'https://ai.wps.cn', sort: 15 },

  { id: '16', name: '飞书文档', icon: '📑', category: '文档处理', subcategory: '协作办公',
    description: '字节跳动飞书内置AI，团队协作首选',
    scenes: ['ai-office'],
    price: '免费', priceDetail: '部分功能免费，企业版付费',
    difficulty: '入门', network: '🇨🇳 国内', mobile: 'iOS/Android',
    pros: '团队协作强、国内生态好、集成字节系',
    cons: '企业功能需付费、AI功能相对基础',
    features: ['智能写作', '会议纪要', '任务跟进', '评论润色', '多维表格'],
    workflow: '协作办公：AI写文档 → 智能润色 → 团队共享 → 评论协作',
    workflowSteps: [
      { step: 1, title: 'AI写文档', desc: 'AI辅助创建和编辑文档' },
      { step: 2, title: '智能润色', desc: 'AI优化文档内容' },
      { step: 3, title: '团队共享', desc: '实时共享给团队成员' },
      { step: 4, title: '评论协作', desc: '评论和协作编辑' }
    ],
    openclaw_practice: '通过飞书开放平台API',
    website: 'https://www.feishu.cn', sort: 16 },

  { id: '17', name: '腾讯文档AI', icon: '📋', category: '文档处理', subcategory: '协作办公',
    description: '腾讯文档内置AI，协作办公好帮手',
    scenes: ['ai-office'],
    price: '免费', priceDetail: '部分功能免费',
    difficulty: '入门', network: '🇨🇳 国内', mobile: 'iOS/Android',
    pros: '腾讯生态集成、国内直连、协作方便',
    cons: 'AI功能相对基础',
    features: ['AI写作', '智能润色', '模板推荐', '团队协作'],
    workflow: '协作文档：AI生成 → 智能润色 → 多人协作',
    workflowSteps: [
      { step: 1, title: 'AI生成', desc: 'AI辅助生成文档内容' },
      { step: 2, title: '智能润色', desc: '一键优化语言' },
      { step: 3, title: '多人协作', desc: '团队成员同时编辑' }
    ],
    openclaw_practice: '通过腾讯文档API',
    website: 'https://docs.qq.com', sort: 17 },

  { id: '18', name: '讯飞文档', icon: '🗣️', category: '文档处理', subcategory: '语音办公',
    description: '科大讯飞文档AI，语音输入+AI处理',
    scenes: ['ai-office'],
    price: '免费', priceDetail: '部分功能免费',
    difficulty: '入门', network: '🇨🇳 国内', mobile: 'iOS/Android',
    pros: '语音输入强、中文优化好、国内直连',
    cons: '功能相对基础',
    features: ['语音转文字', 'AI会议纪要', '智能校对', '多语言翻译'],
    workflow: '语音办公：语音输入 → AI转写 → 智能整理 → 导出文档',
    workflowSteps: [
      { step: 1, title: '语音输入', desc: '通过语音输入内容' },
      { step: 2, title: 'AI转写', desc: '语音实时转为文字' },
      { step: 3, title: '智能整理', desc: 'AI整理优化转写内容' },
      { step: 4, title: '导出文档', desc: '导出为文档保存' }
    ],
    openclaw_practice: '讯飞语音API',
    website: 'https://www.xfyun.cn', sort: 18 },

  { id: '19', name: 'Writeathon', icon: '✍️', category: '文档处理', subcategory: '写作软件',
    description: '专业AI写作工具，适合长文创作',
    scenes: ['ai-office', 'ai-create'],
    price: '免费', priceDetail: '部分免费',
    difficulty: '入门', network: '🇨🇳 国内', mobile: '网页版',
    pros: '长文写作强、专注写作体验、免费使用',
    cons: '功能相对单一',
    features: ['长文写作', '大纲生成', '素材推荐', 'AI润色'],
    workflow: '写作流程：确定主题 → AI生成大纲 → 逐段写作 → AI润色 → 导出',
    workflowSteps: [
      { step: 1, title: '确定主题', desc: '明确写作主题和目标' },
      { step: 2, title: 'AI生成大纲', desc: 'AI生成文章大纲结构' },
      { step: 3, title: '逐段写作', desc: '分段撰写内容' },
      { step: 4, title: 'AI润色', desc: 'AI优化语言和逻辑' },
      { step: 5, title: '导出', desc: '导出为文档' }
    ],
    openclaw_practice: 'Writeathon AI功能',
    website: 'https://www.writeathon.cn', sort: 19 },

  // ===== AI办公 - PPT生成 =====
  { id: '20', name: 'Gamma', icon: '📊', category: 'PPT生成', subcategory: 'AI PPT',
    description: 'AI自动生成PPT，输入主题即可获得完整演示文稿',
    scenes: ['ai-office'],
    price: '付费', priceDetail: '免费有限额，付费约12$/月',
    difficulty: '入门', network: '🌐 全球', mobile: '网页版',
    pros: 'AI生成能力强、模板美观、快速出片',
    cons: '需要网络工具、国内支付不便、中文模板较少',
    features: ['主题生成', 'AI排版', '智能配图', '一键美化', '多语言支持'],
    workflow: 'Gamma工作流：输入主题 → AI生成大纲 → 选择模板 → 自动生成 → 细节调整',
    workflowSteps: [
      { step: 1, title: '输入主题', desc: '用一句话描述PPT主题' },
      { step: 2, title: 'AI生成大纲', desc: 'AI自动生成PPT大纲结构' },
      { step: 3, title: '选择模板', desc: '从模板库选择风格' },
      { step: 4, title: '自动生成', desc: 'AI自动填充内容' },
      { step: 5, title: '细节调整', desc: '手动调整排版、图片' }
    ],
    openclaw_practice: '通过 Gamma API 集成',
    website: 'https://gamma.app', sort: 20 },

  { id: '21', name: 'AiPPT', icon: '🎯', category: 'PPT生成', subcategory: 'AI PPT',
    description: '中文AI PPT生成工具，国内可访问',
    scenes: ['ai-office'],
    price: '免费', priceDetail: '免费有限额，VIP约60$/年',
    difficulty: '入门', network: '🇨🇳 国内', mobile: '网页版',
    pros: '国内可访问、中文优化好、价格便宜',
    cons: '模板美观度一般、AI能力有限',
    features: ['AI生成', '模板选择', '智能排版', '素材库'],
    workflow: '中文PPT流程：输入主题 → AI生成大纲 → 选择模板 → 一键生成',
    workflowSteps: [
      { step: 1, title: '输入主题', desc: '输入PPT主题' },
      { step: 2, title: 'AI生成大纲', desc: 'AI生成大纲' },
      { step: 3, title: '选择模板', desc: '选择PPT模板' },
      { step: 4, title: '一键生成', desc: 'AI自动生成完整PPT' }
    ],
    openclaw_practice: 'AiPPT API',
    website: 'https://aippt.cn', sort: 21 },

  { id: '22', name: '讯飞智文', icon: '🔥', category: 'PPT生成', subcategory: 'AI PPT',
    description: '科大讯飞AI PPT生成，完全免费',
    scenes: ['ai-office'],
    price: '免费', priceDetail: '完全免费',
    difficulty: '入门', network: '🇨🇳 国内', mobile: '网页版',
    pros: '完全免费、国内直连、讯飞语音生态',
    cons: '模板较少、功能相对基础',
    features: ['文档转PPT', 'AI生成', '智能排版'],
    workflow: 'AI PPT流程：输入主题 → 自动生成 → 下载使用',
    workflowSteps: [
      { step: 1, title: '输入主题', desc: '描述PPT主题' },
      { step: 2, title: '自动生成', desc: 'AI自动生成PPT' },
      { step: 3, title: '下载使用', desc: '下载PPT文件' }
    ],
    openclaw_practice: '讯飞智文API',
    website: 'https://zhiwen.xfyun.cn', sort: 22 },

  { id: '23', name: 'Tome', icon: '📖', category: 'PPT生成', subcategory: 'AI PPT',
    description: 'AI驱动PPT生成，故事化演示',
    scenes: ['ai-office', 'ai-create'],
    price: '免费', priceDetail: '免费有限额，付费约8$/月',
    difficulty: '入门', network: '🌐 全球', mobile: '网页版',
    pros: '故事化强、模板现代、适合创意展示',
    cons: '需要网络工具、免费额度有限',
    features: ['AI生成', '故事模式', '交互式幻灯片', '配图生成'],
    workflow: '故事创作流程：输入主题 → AI生成故事 → 选择风格 → 生成幻灯片',
    workflowSteps: [
      { step: 1, title: '输入主题', desc: '描述演示主题' },
      { step: 2, title: 'AI生成故事', desc: 'AI生成叙述性内容' },
      { step: 3, title: '选择风格', desc: '选择视觉风格' },
      { step: 4, title: '生成幻灯片', desc: '生成交互式幻灯片' }
    ],
    openclaw_practice: 'Tome AI',
    website: 'https://tome.app', sort: 23 },

  { id: '24', name: 'Canva AI', icon: '🎨', category: 'PPT生成', subcategory: '设计平台',
    description: 'Canva内置AI设计功能，PPT、海报一体化',
    scenes: ['ai-office', 'ai-create'],
    price: '免费', priceDetail: '免费有限额，Pro版约13$/月',
    difficulty: '入门', network: '🌐 全球', mobile: 'iOS/Android',
    pros: '设计功能强、模板丰富、AI辅助设计',
    cons: '需要网络工具、PPT功能相对较弱',
    features: ['AI生成设计', '智能排版', '素材库', 'PPT制作'],
    workflow: '设计流程：选择尺寸 → AI辅助 → 选择模板 → 导出分享',
    workflowSteps: [
      { step: 1, title: '选择尺寸', desc: '选择设计尺寸(A4/PPT/海报等)' },
      { step: 2, title: 'AI辅助', desc: '描述需求，AI辅助生成' },
      { step: 3, title: '选择模板', desc: '选择模板并调整' },
      { step: 4, title: '导出分享', desc: '导出文件或直接分享' }
    ],
    openclaw_practice: 'Canva AI功能',
    website: 'https://www.canva.com', sort: 24 },

  // ===== AI办公 - 数据分析 =====
  { id: '25', name: 'Excel AI', icon: '📈', category: '数据分析', subcategory: '办公软件',
    description: 'Microsoft Excel内置AI，数据分析更智能',
    scenes: ['ai-office'],
    price: '付费', priceDetail: '需Microsoft 365订阅',
    difficulty: '入门', network: '🌐 全球', mobile: 'iOS/Android',
    pros: '数据分析强大、公式辅助、图表智能生成',
    cons: '需要Microsoft 365、国内访问慢',
    features: ['智能分析', '公式建议', '图表生成', '数据清洗', '预测分析'],
    workflow: '数据分析流程：导入数据 → AI分析建议 → 自动生成图表 → 报告解读',
    workflowSteps: [
      { step: 1, title: '导入数据', desc: '导入Excel数据文件' },
      { step: 2, title: 'AI分析建议', desc: 'AI分析数据并给出建议' },
      { step: 3, title: '自动生成图表', desc: '一键生成可视化图表' },
      { step: 4, title: '报告解读', desc: 'AI解读数据给出洞察' }
    ],
    openclaw_practice: '通过 Microsoft Graph API',
    website: 'https://excel.microsoft.com', sort: 25 },

  { id: '26', name: 'Tableau AI', icon: '📊', category: '数据分析', subcategory: 'BI工具',
    description: 'Salesforce旗下BI工具，AI增强分析',
    scenes: ['ai-office'],
    price: '付费', priceDetail: '约75$/月',
    difficulty: '进阶', network: '🌐 全球', mobile: 'iOS/Android',
    pros: '可视化强、AI分析能力、适合企业',
    cons: '需要网络工具、价格昂贵、学习曲线',
    features: ['AI分析', '智能可视化', '自然语言查询', '数据准备'],
    workflow: 'BI分析流程：连接数据 → AI自动分析 → 生成可视化 → 分享报告',
    workflowSteps: [
      { step: 1, title: '连接数据', desc: '连接各种数据源' },
      { step: 2, title: 'AI自动分析', desc: 'AI自动分析数据模式' },
      { step: 3, title: '生成可视化', desc: '生成交互式可视化' },
      { step: 4, title: '分享报告', desc: '分享给团队成员' }
    ],
    openclaw_practice: 'Tableau AI (Einstein)',
    website: 'https://www.tableau.com', sort: 26 },

  { id: '27', name: 'Power BI', icon: '⚡', category: '数据分析', subcategory: 'BI工具',
    description: '微软BI工具，Copilot赋能AI分析',
    scenes: ['ai-office'],
    price: '免费', priceDetail: '免费版有限，Pro约10$/月',
    difficulty: '进阶', network: '🌐 全球', mobile: 'iOS/Android',
    pros: '微软生态集成、Copilot AI、价格便宜',
    cons: '需要网络工具、功能复杂',
    features: ['Copilot分析', '数据可视化', '报表生成', '自然语言查询'],
    workflow: 'BI流程：导入数据 → Copilot分析 → 生成报表 → 分享协作',
    workflowSteps: [
      { step: 1, title: '导入数据', desc: '导入数据到Power BI' },
      { step: 2, title: 'Copilot分析', desc: '用Copilot自然语言分析' },
      { step: 3, title: '生成报表', desc: '自动生成报表' },
      { step: 4, title: '分享协作', desc: '分享给团队' }
    ],
    openclaw_practice: 'Power BI Copilot',
    website: 'https://powerbi.microsoft.com', sort: 27 },

  // ===== AI创作 - AI图像 =====
  { id: '28', name: 'Midjourney', icon: '🎨', category: 'AI图像', subcategory: '图像生成',
    description: '强大的AI图像生成工具，艺术性强',
    scenes: ['ai-create'],
    price: '付费', priceDetail: '约10$/月',
    difficulty: '进阶', network: '🌐 全球', mobile: '无(Discord)',
    pros: '艺术性强、社区活跃、提示词丰富',
    cons: '需要网络工具、学习曲线陡峭、Discord操作复杂',
    features: ['文生图', '图生图', '局部重绘', '角色一致', '风格迁移'],
    workflow: '图像生成流程：构思场景 → 编写详细提示词 → 调整参数 → 生成 → AI修复',
    workflowSteps: [
      { step: 1, title: '构思', desc: '明确想要生成的画面内容' },
      {