// 工具数据API - 完整版
const tools = [
  // ===== AI入门 - 问答式AI =====
  { id: '1', name: 'ChatGPT', icon: '💬', category: '问答式AI', subcategory: '网页+App',
    description: 'OpenAI开发的AI对话工具，适合日常问答和内容创作',
    scenes: ['ai-entry', 'ai-office', 'ai-create', 'ai-study'],
    price: '免费/付费', priceDetail: '免费版GPT-3.5，付费版GPT-4约20$/月',
    difficulty: '入门', vpn: '需要', mobile: 'iOS/Android',
    pros: '功能全面、社区活跃、插件生态丰富',
    cons: '需要翻墙、付费版较贵、国内支付不便',
    workflow: '入门提示词：描述问题 → AI回答 → 优化提示词 → 获得更好结果',
    openclaw_practice: '通过 OpenAI API skill 调用接口',
    website: 'https://chat.openai.com', sort: 1 },

  { id: '2', name: 'Claude', icon: '🧠', category: '问答式AI', subcategory: '网页+App',
    description: 'Anthropic开发的AI助手，擅长推理和复杂分析，超长上下文',
    scenes: ['ai-entry', 'ai-office', 'ai-study'],
    price: '免费', priceDetail: '免费使用，付费版约25$/月',
    difficulty: '入门', vpn: '需要', mobile: 'iOS/Android',
    pros: '推理能力强、长文本处理优秀、输出安全',
    cons: '需要翻墙、国内支付不便、偶尔响应慢',
    workflow: '深度推理：提出复杂问题 → AI分析 → 追问细节 → 获得深入解答',
    openclaw_practice: '通过 Anthropic API skill 调用',
    website: 'https://claude.ai', sort: 2 },

  { id: '3', name: 'Gemini', icon: '🌟', category: '问答式AI', subcategory: '网页+App',
    description: 'Google推出的多模态AI，支持图像理解和生成',
    scenes: ['ai-entry', 'ai-create'],
    price: '免费', priceDetail: '免费版有限额，付费版约20$/月',
    difficulty: '入门', vpn: '需要', mobile: 'iOS/Android',
    pros: '多模态能力强、Google生态集成、免费额度多',
    cons: '需要翻墙、国内版功能受限',
    workflow: '多模态交互：文本+图像 → 综合理解 → 多形式输出',
    openclaw_practice: '通过 Google Gemini API',
    website: 'https://gemini.google.com', sort: 3 },

  { id: '4', name: '通义千问', icon: '🐰', category: '问答式AI', subcategory: '网页+App',
    description: '阿里推出的中文AI助手，针对中文场景优化',
    scenes: ['ai-entry', 'ai-office', 'ai-study'],
    price: '免费', priceDetail: '免费使用',
    difficulty: '入门', vpn: '不需要', mobile: 'iOS/Android',
    pros: '中文优化好、国内可访问、完全免费',
    cons: '英文能力较弱、推理能力不如Claude',
    workflow: '中文办公：PPT大纲 → 自动生成 → AI配图 → 智能排版',
    openclaw_practice: '通过 阿里云API 集成',
    website: 'https://tongyi.aliyun.com', sort: 4 },

  { id: '5', name: 'Kimi', icon: '🌙', category: '问答式AI', subcategory: '网页+App',
    description: '月之暗面推出的长文本AI，支持超长上下文，200万字',
    scenes: ['ai-entry', 'ai-office', 'ai-study'],
    price: '免费', priceDetail: '免费使用，付费版约50$/月',
    difficulty: '入门', vpn: '不需要', mobile: 'iOS/Android',
    pros: '长文本能力极强、中文理解好、完全免费',
    cons: '推理能力不如Claude、起步较晚',
    workflow: '长文本处理：上传文档 → AI总结 → 问答互动 → 深度理解',
    openclaw_practice: '通过 Kimi API',
    website: 'https://kimi.moonshot.cn', sort: 5 },

  { id: '6', name: '文心一言', icon: '🦅', category: '问答式AI', subcategory: '网页+App',
    description: '百度推出的中文AI助手，文学创作能力强',
    scenes: ['ai-entry', 'ai-office'],
    price: '免费', priceDetail: '免费使用，付费版约60$/年',
    difficulty: '入门', vpn: '不需要', mobile: 'iOS/Android',
    pros: '中文理解好、国内可访问、文学创作能力强',
    cons: '推理能力较弱、偶尔回答质量不稳定',
    workflow: '中文创作：输入主题 → AI生成 → 润色修改 → 导出',
    openclaw_practice: '通过 百度文心API',
    website: 'https://yiyan.baidu.com', sort: 6 },

  { id: '7', name: '讯飞星火', icon: '🔥', category: '问答式AI', subcategory: '网页+App',
    description: '科大讯飞推出的AI助手，语音能力突出',
    scenes: ['ai-entry', 'ai-office'],
    price: '免费', priceDetail: '免费使用',
    difficulty: '入门', vpn: '不需要', mobile: 'iOS/Android',
    pros: '语音能力强、中文理解好、国内可访问',
    cons: '推理能力一般、回答有时过于简短',
    workflow: '语音输入：语音转文字 → AI处理 → 语音输出',
    openclaw_practice: '通过 讯飞星火API',
    website: 'https://xinghuo.xfyun.com', sort: 7 },

  { id: '8', name: 'Perplexity', icon: '🔍', category: 'AI搜索', subcategory: '网页+App',
    description: 'AI搜索引擎，结合GPT-4提供实时精准答案',
    scenes: ['ai-entry', 'ai-study'],
    price: '免费', priceDetail: '免费版有限额，付费版约20$/月',
    difficulty: '入门', vpn: '需要', mobile: 'iOS/Android',
    pros: '实时联网、答案有来源、学术搜索强',
    cons: '需要翻墙、免费额度有限',
    workflow: '学术研究：输入课题 → AI搜索整合 → 获取摘要 → 深入阅读 → 笔记整理',
    openclaw_practice: '通过 Perplexity API',
    website: 'https://www.perplexity.ai', sort: 8 },

  { id: '9', name: '秘塔搜索', icon: '🔎', category: 'AI搜索', subcategory: '网页+App',
    description: '中文AI搜索引擎，无广告',
    scenes: ['ai-entry', 'ai-study'],
    price: '免费', priceDetail: '完全免费',
    difficulty: '入门', vpn: '不需要', mobile: 'iOS/Android',
    pros: '中文优化好、无广告、免费使用',
    cons: '功能相对基础、偶尔响应慢',
    workflow: '中文搜索：输入问题 → AI整理 → 结构化答案 → 深入了解',
    openclaw_practice: '秘塔AI搜索',
    website: 'https://metaso.cn', sort: 9 },

  { id: '10', name: '360智脑', icon: '🔵', category: '问答式AI', subcategory: '网页+App',
    description: '360推出的AI助手，性价比高',
    scenes: ['ai-entry', 'ai-office'],
    price: '免费', priceDetail: '免费使用',
    difficulty: '入门', vpn: '不需要', mobile: 'iOS/Android',
    pros: '国内可访问、免费使用、360生态',
    cons: '功能相对基础、品牌信任度一般',
    workflow: '日常问答：输入问题 → AI回答 → 追问优化',
    openclaw_practice: '通过 360智脑API',
    website: 'https://ai.360.cn', sort: 10 },

  // ===== AI入门 - AI模型 =====
  { id: '11', name: 'GPT-4', icon: '🔮', category: 'AI模型', subcategory: 'API',
    description: 'OpenAI最强大的语言模型，适合高质量内容生成',
    scenes: ['ai-entry'],
    price: '付费', priceDetail: '约20$/月(Plus)或按量付费',
    difficulty: '进阶', vpn: '需要', mobile: '无',
    pros: '能力最强、插件生态、图像理解',
    cons: '需要翻墙、费用较高',
    workflow: 'API调用：设置角色 → 发送请求 → 处理响应 → 结果优化',
    openclaw_practice: '通过 OpenAI API skill 调用 GPT-4',
    website: 'https://platform.openai.com', sort: 11 },

  { id: '12', name: 'Claude 3', icon: '📦', category: 'AI模型', subcategory: 'API',
    description: 'Anthropic最新模型，超长上下文200K token',
    scenes: ['ai-entry'],
    price: '付费', priceDetail: '约25$/月或按量付费',
    difficulty: '进阶', vpn: '需要', mobile: '无',
    pros: '推理能力强、长上下文、安全性好',
    cons: '需要翻墙、国内支付不便',
    workflow: '企业应用：数据分析 → 报告生成 → 决策支持',
    openclaw_practice: '通过 Claude API',
    website: 'https://www.anthropic.com', sort: 12 },

  // ===== AI办公 - 文档处理 =====
  { id: '13', name: 'Notion AI', icon: '📝', category: '文档处理', subcategory: '笔记软件',
    description: 'Notion内置AI功能，帮助写作和整理笔记',
    scenes: ['ai-office', 'ai-study'],
    price: '付费', priceDetail: '约10$/月',
    difficulty: '入门', vpn: '需要', mobile: 'iOS/Android',
    pros: '笔记+AI完美结合、模板丰富、协作方便',
    cons: '需要翻墙、国内访问慢、付费较贵',
    workflow: '写作工作流：AI生成大纲 → 撰写初稿 → AI润色 → 自动整理 → 导出分享',
    openclaw_practice: '通过飞书+Notion API 联动',
    website: 'https://notion.so/product/ai', sort: 13 },

  { id: '14', name: 'WPS AI', icon: '📄', category: '文档处理', subcategory: '办公软件',
    description: '金山WPS内置AI，中文办公更顺手',
    scenes: ['ai-office'],
    price: '免费', priceDetail: '部分功能免费，会员约30$/年',
    difficulty: '入门', vpn: '不需要', mobile: 'iOS/Android',
    pros: '国内可访问、中文优化好、免费功能多',
    cons: 'AI功能相对基础、付费版AI功能有限',
    workflow: '文档处理：AI续写 → 智能排版 → 内容润色 → 一键生成',
    openclaw_practice: '通过 WPS AI API',
    website: 'https://ai.wps.cn', sort: 14 },

  { id: '15', name: '飞书文档', icon: '📑', category: '文档处理', subcategory: '协作办公',
    description: '字节跳动飞书内置AI，团队协作首选',
    scenes: ['ai-office'],
    price: '免费', priceDetail: '部分功能免费，企业版付费',
    difficulty: '入门', vpn: '不需要', mobile: 'iOS/Android',
    pros: '团队协作强、国内生态好、集成字节系',
    cons: '企业功能需付费、AI功能相对基础',
    workflow: '协作办公：AI写文档 → 智能润色 → 团队共享 → 评论协作',
    openclaw_practice: '通过飞书开放平台API',
    website: 'https://www.feishu.cn', sort: 15 },

  // ===== AI办公 - PPT生成 =====
  { id: '16', name: 'Gamma', icon: '📊', category: 'PPT生成', subcategory: 'AI PPT',
    description: 'AI自动生成PPT，输入主题即可获得完整演示文稿',
    scenes: ['ai-office'],
    price: '付费', priceDetail: '免费有限额，付费约12$/月',
    difficulty: '入门', vpn: '需要', mobile: '网页版',
    pros: 'AI生成能力强、模板美观、快速出片',
    cons: '需要翻墙、国内支付不便、中文模板较少',
    workflow: 'PPT工作流：输入主题 → AI生成大纲 → 选择模板 → 自动生成 → 细节调整',
    openclaw_practice: '通过 Gamma API 集成',
    website: 'https://gamma.app', sort: 16 },

  { id: '17', name: 'AiPPT', icon: '🎯', category: 'PPT生成', subcategory: 'AI PPT',
    description: '中文AI PPT生成工具，国内可访问',
    scenes: ['ai-office'],
    price: '免费', priceDetail: '免费有限额，VIP约60$/年',
    difficulty: '入门', vpn: '不需要', mobile: '网页版',
    pros: '国内可访问、中文优化好、价格便宜',
    cons: '模板美观度一般、AI能力有限',
    workflow: '中文PPT：输入主题 → AI生成大纲 → 选择模板 → 一键生成',
    openclaw_practice: 'AiPPT API',
    website: 'https://aippt.cn', sort: 17 },

  // ===== AI创作 - AI图像 =====
  { id: '18', name: 'Midjourney', icon: '🎨', category: 'AI图像', subcategory: '图像生成',
    description: '强大的AI图像生成工具，艺术性强',
    scenes: ['ai-create'],
    price: '付费', priceDetail: '约10$/月',
    difficulty: '进阶', vpn: '需要', mobile: '无(Discord)',
    pros: '艺术性强、社区活跃、提示词丰富',
    cons: '需要翻墙、学习曲线陡峭、Discord操作复杂',
    workflow: '图像生成：构思场景 → 编写详细提示词 → 调整参数 → 生成 → AI修复',
    openclaw_practice: '通过 DALL-E skill 实践',
    website: 'https://www.midjourney.com', sort: 18 },

  { id: '19', name: 'DALL-E 3', icon: '🖼️', category: 'AI图像', subcategory: '图像生成',
    description: 'OpenAI图像生成，GPT集成更智能',
    scenes: ['ai-create'],
    price: '付费', priceDetail: '约15$/100张',
    difficulty: '入门', vpn: '需要', mobile: '网页版',
    pros: 'GPT集成、生成稳定、安全性好',
    cons: '需要翻墙、艺术性不如MJ、价格较贵',
    workflow: '图像+文本：描述需求 → GPT优化提示词 → DALL-E生成 → 编辑',
    openclaw_practice: '通过 DALL-E API',
    website: 'https://openai.com/dall-e-3', sort: 19 },

  { id: '20', name: 'Stable Diffusion', icon: '⚡', category: 'AI图像', subcategory: '本地部署',
    description: '开源本地运行，可自定义模型，完全免费',
    scenes: ['ai-create'],
    price: '免费', priceDetail: '需要显卡硬件',
    difficulty: '进阶', vpn: '不需要', mobile: '无',
    pros: '完全免费、本地部署可控、可训练模型',
    cons: '需要显卡硬件、配置复杂、学习曲线陡峭',
    workflow: '本地部署：安装模型 → 编写提示词 → 参数调整 → 本地生成',
    openclaw_practice: '通过 ComfyUI 工作流',
    website: 'https://stability.ai', sort: 20 },

  { id: '21', name: 'Liblib', icon: '💜', category: 'AI图像', subcategory: '国内平台',
    description: '国内AI图像社区，免费模型丰富',
    scenes: ['ai-create'],
    price: '免费', priceDetail: '部分免费，部分付费',
    difficulty: '入门', vpn: '不需要', mobile: '网页版',
    pros: '国内可访问、中文界面、免费模型多',
    cons: '生成速度有时慢、个别模型需付费',
    workflow: '国内AI绘图：选择模型 → 编写提示词 → 一键生成 → 下载',
    openclaw_practice: 'Liblib API',
    website: 'https://www.liblib.art', sort: 21 },

  // ===== AI创作 - AI视频 =====
  { id: '22', name: 'Runway', icon: '🎬', category: 'AI视频', subcategory: '视频生成',
    description: 'AI视频生成和编辑，功能全面',
    scenes: ['ai-create'],
    price: '付费', priceDetail: '约15$/月',
    difficulty: '进阶', vpn: '需要', mobile: 'iOS',
    pros: '功能全面、视频质量高、编辑能力强',
    cons: '需要翻墙、价格较贵、免费额度少',
    workflow: '视频创作：ChatGPT写文案 → Midjourney配图 → Runway生成视频 → AI配音 → 后期',
    openclaw_practice: '通过 Runway API',
    website: 'https://runway.ml', sort: 22 },

  { id: '23', name: 'Pika', icon: '📽️', category: 'AI视频', subcategory: '视频生成',
    description: '文字转视频，新手友好，完全免费',
    scenes: ['ai-create'],
    price: '免费', priceDetail: '免费使用',
    difficulty: '入门', vpn: '需要', mobile: '网页版',
    pros: '完全免费、操作简单、新手友好',
    cons: '需要翻墙、视频长度有限、质量一般',
    workflow: '文字转视频：输入描述 → 选择风格 → AI生成 → 预览',
    openclaw_practice: '通过 Pika API',
    website: 'https://pika.art', sort: 23 },

  { id: '24', name: 'HeyGen', icon: '👤', category: 'AI视频', subcategory: '数字人',
    description: '数字人视频生成，适合营销和培训',
    scenes: ['ai-create'],
    price: '付费', priceDetail: '约30$/月',
    difficulty: '入门', vpn: '需要', mobile: '网页版',
    pros: '数字人逼真、支持多语言、适合营销',
    cons: '需要翻墙、价格较贵、免费额度少',
    workflow: '数字人：选择形象 → 输入文案 → AI驱动 → 视频导出',
    openclaw_practice: '通过 HeyGen API',
    website: 'https://heygen.com', sort: 24 },

  // ===== AI编程 - IDE插件 =====
  { id: '25', name: 'GitHub Copilot', icon: '💻', category: 'IDE插件', subcategory: '代码补全',
    description: 'AI代码助手，代码补全首选',
    scenes: ['ai-code'],
    price: '付费', priceDetail: '约10$/月',
    difficulty: '进阶', vpn: '需要', mobile: '无',
    pros: '补全准确、支持多语言、社区支持好',
    cons: '需要翻墙、付费较贵、隐私担忧',
    workflow: '编程工作流：描述需求 → AI生成代码 → Copilot补全 → AI Debug → 完成',
    openclaw_practice: '通过 VS Code 集成',
    website: 'https://github.com/features/copilot', sort: 25 },

  { id: '26', name: 'Codeium', icon: '⚡', category: 'IDE插件', subcategory: '代码补全',
    description: '免费AI编程助手，Copilot替代',
    scenes: ['ai-code'],
    price: '免费', priceDetail: '免费使用，付费版约10$/月',
    difficulty: '入门', vpn: '不需要', mobile: '无',
    pros: '完全免费、国内可访问、功能全面',
    cons: '免费版功能有限、偶尔不稳定',
    workflow: '免费补全：安装插件 → 登录 → 自动补全 → 代码生成',
    openclaw_practice: 'Codeium 免费使用',
    website: 'https://codeium.com', sort: 26 },

  // ===== AI编程 - 编程工具 =====
  { id: '27', name: 'Cursor', icon: '🎯', category: '编程工具', subcategory: 'AI IDE',
    description: 'AI优先的代码编辑器，基于VS Code',
    scenes: ['ai-code'],
    price: '免费', priceDetail: '免费版有限额，付费版约20$/月',
    difficulty: '入门', vpn: '不需要', mobile: '无',
    pros: '免费额度多、国内可访问、操作类似VS Code',
    cons: '付费版功能提升有限、偶尔响应慢',
    workflow: 'AI编程：描述功能 → AI编写代码 → 预览效果 → 迭代修改 → 完成',
    openclaw_practice: '内置 AI 编程功能',
    website: 'https://cursor.sh', sort: 27 },

  { id: '28', name: 'Claude Code', icon: '🧬', category: '编程工具', subcategory: 'CLI工具',
    description: 'Anthropic编程助手，擅长复杂逻辑',
    scenes: ['ai-code'],
    price: '免费', priceDetail: '免费使用',
    difficulty: '入门', vpn: '需要', mobile: '无',
    pros: '完全免费、推理能力强、适合复杂任务',
    cons: '需要翻墙、CLI操作有门槛',
    workflow: '代码开发：描述需求 → AI分析 → 生成代码 → 调试优化 → 交付',
    openclaw_practice: 'Claude Code CLI',
    website: 'https://claude.com/claude-code', sort: 28 },

  { id: '29', name: 'Windsurf', icon: '🌊', category: '编程工具', subcategory: 'AI IDE',
    description: 'Codeium推出的AI编辑器',
    scenes: ['ai-code'],
    price: '付费', priceDetail: '约10$/月',
    difficulty: '入门', vpn: '不需要', mobile: '无',
    pros: '免费版功能多、国内可访问、AI功能强',
    cons: '付费版价格适中、相对较新',
    workflow: 'AI编辑：打开项目 → AI理解代码 → 智能补全 → 快速重构',
    openclaw_practice: 'Windsurf AI 功能',
    website: 'https://windsurf.com', sort: 29 },

  // ===== AI学习 - 论文阅读 =====
  { id: '30', name: 'Scholarcy', icon: '📚', category: '论文阅读', subcategory: '论文摘要',
    description: 'AI论文摘要工具，快速了解论文要点',
    scenes: ['ai-study'],
    price: '免费', priceDetail: '免费有限额，付费约10$/月',
    difficulty: '入门', vpn: '需要', mobile: '无',
    pros: '自动摘要快、提取图表、问答功能',
    cons: '需要翻墙、免费额度有限',
    workflow: '论文阅读：上传PDF → AI生成摘要 → 提取图表 → 问答互动',
    openclaw_practice: '通过 Scholarcy API',
    website: 'https://www.scholarcy.com', sort: 30 },

  { id: '31', name: 'Zotero AI', icon: '📖', category: '论文阅读', subcategory: '文献管理',
    description: 'Zotero内置AI，文献管理+AI分析',
    scenes: ['ai-study'],
    price: '免费', priceDetail: '插件免费，Zotero基础版免费',
    difficulty: '入门', vpn: '不需要', mobile: '无',
    pros: '文献管理强大、开源免费、插件丰富',
    cons: '配置稍复杂、AI功能相对基础',
    workflow: '文献研究：导入文献 → AI分析 → 笔记整理 → 写作引用',
    openclaw_practice: 'Zotero AI插件',
    website: 'https://www.zotero.org', sort: 31 },

  // ===== AI学习 - 笔记整理 =====
  { id: '32', name: 'Obsidian AI', icon: '💎', category: '笔记整理', subcategory: '双向链接',
    description: '双向链接笔记+AI辅助思考',
    scenes: ['ai-study'],
    price: '免费', priceDetail: '插件免费，云服务付费',
    difficulty: '入门', vpn: '不需要', mobile: 'iOS/Android',
    pros: '本地优先、插件丰富、AI辅助思考',
    cons: '需要配置、AI插件需付费',
    workflow: '知识管理：记录笔记 → AI关联 → 思维导图 → 深度理解',
    openclaw_practice: '通过 Obsidian Plugins',
    website: 'https://obsidian.md', sort: 32 },

  { id: '33', name: 'Logseq', icon: '📋', category: '笔记整理', subcategory: '大纲笔记',
    description: '大纲笔记+AI，大纲式思考',
    scenes: ['ai-study'],
    price: '免费', priceDetail: '完全免费',
    difficulty: '入门', vpn: '不需要', mobile: 'iOS/Android',
    pros: '完全免费、大纲式思考、本地优先',
    cons: '功能相对基础、插件较少',
    workflow: '知识整理：记录要点 → AI扩展 → 结构化 → 导出分享',
    openclaw_practice: '通过 Logseq AI 插件',
    website: 'https://logseq.com', sort: 33 }
]

const scenes = [
  { id: 'ai-entry', name: 'AI入门', icon: '🚀', description: '零基础用户不知道怎么开始学习AI' },
  { id: 'ai-office', name: 'AI办公', icon: '💼', description: '日常办公场景' },
  { id: 'ai-create', name: 'AI创作', icon: '🎨', description: '写文章，做视频、生成图片' },
  { id: 'ai-code', name: 'AI编程', icon: '💻', description: '代码辅助、调试，Bug修复' },
  { id: 'ai-study', name: 'AI学习', icon: '📚', description: '看论文、学新技术' }
]

export default function handler(req, res) {
  const { scene } = req.query
  
  let result = tools
  
  // 按场景过滤
  if (scene) {
    result = tools.filter(t => t.scenes.includes(scene))
  }
  
  // 返回数据
  res.status(200).json({
    success: true,
    data: result,
    scenes: scenes
  })
}
